import clsx from "clsx";
import type { Metadata } from "next";

import "normalize.css";
import "./globals.scss";

import { MontserratFont } from "@/shared/lib";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={clsx(MontserratFont.className)}>{children}</body>
    </html>
  );
}
